### ISSUE TITLE
建议增加域名解析的console界面截图

### ISSUE THREAD

**Issue by yixiaoer2012** [huaweicloudDocs/dns#1]
1、建议增加域名解析的console界面截图
2、记录集是什么？为什么不用业界通用的说法？

**Comment by zhfreal** [comment]
文档应付了事，域名解析转移至华为，帮助文档不写华为的NS记录值，查个NS都找不到地方，你们真行

**Comment by chengnan6** [comment]
> 文档应付了事，域名解析转移至华为，帮助文档不写华为的NS记录值，查个NS都找不到地方，你们真行

文档中已经补充DNS的NS值，并给出到对应设置页面的链接：
![image](https://user-images.githubusercontent.com/58577979/133866882-674a4244-0a34-456c-8007-268eab839a08.png)
